### ISSUE TITLE
Blockade destroy should quit with error if not executed with root privileges

### ISSUE THREAD

**Issue by szborows** [dcm-oss/blockade#26]
Currently the execution happily passes straight into iptables setup and throws meaningless exception from subprocess.check_output - OSError File does not exist

**Comment by labisso** [comment]
With the (imminent) 0.3.0 release, root privileges are no longer required. Iptables and tc commands are themselves executed in docker containers. So the user just needs the ability to call docker.

It's still not the most beautiful error if the user _doesn't_ have Docker privileges, so I'm going to keep this issue open and add a friendlier error in a future release.
