### ISSUE TITLE
OSX: blockade.yml doesn't work, blockade.yaml does

### ISSUE THREAD

**Issue by kklocek** [dcm-oss/blockade#43]
Hello!

I read blockade guide, however I was stuck on creating `blockade.yml` file. When I save it and run `blockade up` in response I got:
` NODE            CONTAINER ID    STATUS  IP              NETWORK    PARTITION`

However if I changed file name to `blockade.yaml` it works fine.

I have a fix to docs (just one character...) but is it not an internal issue?

I used blockade file from ==> http://blockade.readthedocs.io/en/latest/guide.html
OS: macOS Sierra 10.12.1
Docker version: 
Version 1.12.3 (13776)
Channel: Stable
583d1b8ffe

**Comment by labisso** [comment]
Yes you are right. this is a bug introduced in a recent refactor. Either `yaml` or `yml` extension are supposed to work. I'll fix it soon but merge your doc PR first to avoid other people having the same confusion. Thanks!
